# Generated by Django 4.2 on 2023-05-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_actualizado',
        ),
    ]
